name: Swift

on:
  pull_request:
    branches: [ master ]

jobs:
  cancel-previous:
      runs-on: ubuntu-latest
      steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          
  build-and-test:
    needs: [cancel-previous]
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
